# Site settings
title: Kite SDK Development Guide
email: cdk-dev@cloudera.org
description: "Documentation for the Kite open source project on GitHub."
baseurl: "/docs/current/guide"
url: "http://kitesdk.org"
include: ["./samples/"]
dataset-command: "kite-dataset"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  coderay_line_numbers: table
  

